require 'rake'

environment = 'prod'

cmd_google_registry_push = "docker push " +
    "#{$project['google_user']}/#{$project['project_id']}/#{$project['google_repo']}_#{environment}:#{$project['version']}"

cmd_google_registry_tag = "docker tag " +
    "#{$project['local_user']}/#{$project['project']}:#{environment} #{$project['google_user']}/#{$project['project_id']}/#{$project['google_repo']}_#{environment}:#{$project['version']}"

namespace :google do
  namespace :prod do
    namespace :registry do

      desc 'Push production image to google.com'
      task :push do
        $commands << cmd_google_registry_push
      end

      desc 'Tag production image for google.com'
      task :tag do
        $commands << cmd_google_registry_tag
      end

    end
  end
end