# frozen_string_literal: true

require 'rake'

environment = 'prod'
vm_name = "#{@project['google_repo']}-#{environment}"

cmd_google_registry_push = 'docker push ' \
    "#{@project['google_user']}/#{@project['project_id']}/#{vm_name}:" \
    "#{@project['version']}"

cmd_google_registry_tag = 'docker tag ' \
    "#{@project['local_user']}/#{@project['project']}:#{environment} " \
    "#{@project['google_user']}/#{@project['project_id']}/#{vm_name}:" \
    "#{@project['version']}"

namespace :google do
  namespace :prod do
    namespace :registry do
      desc 'Push production image to google.com'
      task :push do
        @commands << cmd_google_registry_push
      end

      desc 'Tag production image for google.com'
      task :tag do
        @commands << cmd_google_registry_tag
      end
    end
  end
end
