# frozen_string_literal: true

namespace :project do
  desc 'Create and deploy prod image to dockerhub'
  task prod: %w[git:warn
                dockerhub:login
                rubylint
                ansible:prod:lint
                images:project:update
                images:project:prod:build
                images:project:prod:molecule:test
                git:tag
                dockerhub:tag
                dockerhub:push]
end
