---
# project settings
name: takelage-bit
version: 0.6.11
local_user: packer_local

# dockerhub settings for the base image
dockerhub_base_user: takelage
dockerhub_base_repo: takelbase

# dockerhub settings
dockerhub_user: takelage
dockerhub_repo: bitboard
dockerhub_tag: prod
ssh_port: 222

# google production settings
google_firewall_prod: []
