---
# project settings
name: takelage-bit
version: 0.7.5

pipelines:
  - prod

local_user: packer_local

images:
  project:
    base_user: takelage
    base_repo: takelbase
    base_tag: latest
    target_user: takelage
    target_repo: bitboard
    omit_pipeline_name: prod
    layers:
      - site
    command: /lib/systemd/systemd
    packer_command: /lib/systemd/systemd
    privileged: --privileged
  bitslim:
    base_user: takelage
    base_repo: takelslim
    base_tag: latest
    target_user: takelage
    target_repo: bitslim
    omit_pipeline_name: prod
    layers:
      - site
    command: /usr/sbin/sshd -D -e

# system settings
ssh_port: 222

# google production settings
google_firewall_prod: []
