---
# project settings
name: takelage-bit
version: 0.9.4

local_user: packer_local

images:
  project:
    base_user: takelwerk
    base_repo: takelslim
    base_tag: latest
    target_user: takelwerk
    target_repo: bitboard
    layers:
      - site
    command: /usr/sbin/sshd -D -e
  bitserver:
    base_user: takelwerk
    base_repo: takelbase
    base_tag: latest
    target_user: takelwerk
    target_repo: bitserver
    layers:
      - site
    command: /lib/systemd/systemd
    packer_command: /lib/systemd/systemd
    privileged: --privileged

# system settings
ssh_port: 222

# google production settings
google_firewall_prod: []
