---
# project settings
name: takelage-bit
version: 0.7.1

pipelines:
  - prod

images:
  bitboard:
    layers:
      - site
    run_command: /lib/systemd/systemd
    privileged: --privileged

# results in packer_local/myproject-mypipeline:latest
local_user: packer_local

# pull
dockerhub_base_user: takelage
dockerhub_base_repo: takelbase

# push
dockerhub_user: takelage
dockerhub_repo: bitboard
dockerhub_tag: latest

# system settings
ssh_port: 222

# google production settings
google_firewall_prod: []
