require 'rake'

cmd_dockerhub_prod_registry_login = 'docker login'

cmd_dockerhub_prod_registry_push = 'docker push ' +
    "#{$project['username_dockerhub']}/#{$project['repo_dockerhub_prod']}:#{$project['version']} && " +
    'docker push ' +
    "#{$project['username_dockerhub']}/#{$project['repo_dockerhub_prod']}:latest"

cmd_dockerhub_prod_registry_tag = 'docker tag ' +
    "#{$project['repo_local']}/#{$project['project']}:prod #{$project['username_dockerhub']}/#{$project['repo_dockerhub_prod']}:#{$project['version']} && " +
    'docker tag ' +
    "#{$project['repo_local']}/#{$project['project']}:prod #{$project['username_dockerhub']}/#{$project['repo_dockerhub_prod']}:latest"

namespace :dockerhub do
  namespace :prod do
    namespace :registry do

      desc 'Log in to hub.docker.com'
      task :login do
        $commands << cmd_dockerhub_prod_registry_login
      end

      desc 'Push production image to hub.docker.com'
      task :push do
        $commands << cmd_dockerhub_prod_registry_push
      end

      desc 'Tag production image for hub.docker.com'
      task :tag do
        $commands << cmd_dockerhub_prod_registry_tag
      end

    end
  end
end
