# frozen_string_literal: true

require 'rake'

cmd_local_container_id = 'tau docker container check existing ' \
    "#{@project['name']} && " \
    "docker exec #{@project['name']}_local hostname" \
    '; true'

cmd_local_container_start = 'tau docker container check existing ' \
    "#{@project['name']} || " \
    'docker run ' \
    '--detach ' \
    "--name #{@project['name']}_local " \
    "--network #{ENV['HOSTNAME']} " \
    '--privileged ' \
    '--rm ' \
    "#{@project['local_user']}/#{@project['name']}-project-prod" \
    '; true'

cmd_local_container_stop = 'tau docker container check existing ' \
    "#{@project['name']} && " \
    'docker stop ' \
    "#{@project['name']}_local" \
    '; true'

namespace :local do
  namespace :container do
    desc 'Get the local container id'
    task :id do
      @commands << cmd_local_container_id
    end

    desc 'Start local container'
    task :start do
      @commands << cmd_local_container_start
    end

    desc 'Stop local container'
    task :stop do
      @commands << cmd_local_container_stop
    end
  end
end
