require 'rake'

desc 'Create and deploy app to production'
task :prod => %w(test
                 local:container:stop
                 image:prod:build
                 image:prod:test
                 git:tag
                 dockerhub:registry:tag
                 dockerhub:registry:login
                 dockerhub:registry:push)
