require 'rake'

desc 'Create and deploy app to production'
task :prod => %w(image:base:debian_10_systemd
                 test
                 local:container:stop
                 image:prod:build
                 image:prod:test
                 git:tag
                 dockerhub:registry:tag
                 dockerhub:registry:push)
