# frozen_string_literal: true

require 'rake'

@gce_container = {
  create: 'gcloud compute instances ' \
          'create-with-container ' \
          "#{@project['google_repo']}-%<project_environment>s " \
          "--address=#{@project['ip_prod']} " \
          '--container-image= ' \
          "#{@project['google_user']}/#{@project['google_id']}/" \
          "#{@project['google_repo']}-%<project_environment>s:" \
          "#{@project['version']} " \
          '--container-privileged ' \
          "--machine-type=#{@project['machine_type_prod']} " \
          "--boot-disk-size=#{@project['boot_disk_size_prod']} " \
          "--project=#{@project['google_id']} " \
          '--scopes=storage-full ' \
          "--tags=#{@project['google_repo']}-%<project_environment>s " \
          "--zone=#{@project['google_zone']} ",
  list: 'gcloud compute instances list ' \
        "--project=#{@project['google_id']} ",
  update: 'gcloud compute instances ' \
          'update-container ' \
          "#{@project['google_repo']}-%<project_environment>s " \
          "--container-image=#{@project['google_user']}/" \
          "#{@project['google_id']}/" \
          "#{@project['google_repo']}-%<project_environment>s:" \
          "#{@project['version']} " \
          '--container-privileged ' \
          "--zone=#{@project['google_zone']} " \
          "--project=#{@project['google_id']} "
}

namespace :cloud do
  namespace :gce do |gce_env|
    subtasks(gce_env.scope.path) do
      @project['pipelines'].each do |pipeline|
        namespace pipeline.to_sym do |env|
          namespace :container do
            @gce_container.each do |task, command|
              desc "#{task} container in GCE"
              task task do
                @commands << format(
                  command,
                  project_environment: env.scope.head
                )
              end
            end
          end
        end
      end
    end
  end
end
