require 'rake'

image = "#{$project['google_user']}/#{$project['project_id']}/#{$project['google_repo']}:#{$project['version']}"

# https://cloud.google.com/sdk/gcloud/reference/compute/instances/create-with-container
cmd_google_container_deploy = "gcloud compute instances create-with-container #{$project['google_repo']} " +
    "--address=#{$project['ip']} " +
    "--container-image=#{image} " +
    "--container-privileged " +
    "--machine-type=#{$project['machine_type']} " +
    "--project=#{$project['project_id']} " +
    "--public-ptr " +
    "--scopes=storage-full " +
    "--tags=#{$project['google_repo']} " +
    "--zone=#{$project['zone']} "

cmd_google_container_list = "gcloud compute instances list " +
    "--project=#{$project['project_id']} "

cmd_google_container_update = "gcloud compute instances update-container #{$project['google_repo']} " +
    "--container-image=#{image} " +
    "--container-privileged " +
    "--zone=#{$project['zone']} " +
    "--project=#{$project['project_id']} "

namespace :google do
  namespace :prod do
    namespace :container do

      desc 'Deploy and start container in GCE'
      task :create do
        $commands << cmd_google_container_deploy
      end

      desc 'List compute instances in GCE'
      task :list do
        $commands << cmd_google_container_list
      end

      desc 'Update and restart container in GCE'
      task :update do
        $commands << cmd_google_container_update
      end

    end
  end
end