# frozen_string_literal: true

require 'rake'

environment = 'prod'
ip = @project['ip_prod'].to_s
vm_name = "#{@project['google_repo']}-#{environment}"
machine_type = @project['machine_type_prod'].to_s
boot_disk_size = @project['boot_disk_size_prod'].to_s

image = "#{@project['google_user']}/#{@project['project_id']}/#{vm_name}:" \
        "#{@project['version']}"

# https://cloud.google.com/sdk/gcloud/reference/compute/instances/create-with-container
cmd_google_container_deploy = 'gcloud compute instances ' \
    "create-with-container #{vm_name} " \
    "--address=#{ip} " \
    "--container-image=#{image} " \
    '--container-privileged ' \
    "--machine-type=#{machine_type} " \
    "--boot-disk-size=#{boot_disk_size} " \
    "--project=#{@project['project_id']} " \
    '--scopes=storage-full ' \
    "--tags=#{@project['google_repo']}-#{environment} " \
    "--zone=#{@project['zone']} "

cmd_google_container_list = 'gcloud compute instances list ' \
    "--project=#{@project['project_id']} "

cmd_google_container_update = 'gcloud compute instances ' \
    "update-container #{vm_name} " \
    "--container-image=#{image} " \
    '--container-privileged ' \
    "--zone=#{@project['zone']} " \
    "--project=#{@project['project_id']} "

namespace :google do
  namespace :prod do
    namespace :container do
      desc 'Deploy and start container in GCE'
      task :create do
        @commands << cmd_google_container_deploy
      end

      desc 'List compute instances in GCE'
      task :list do
        @commands << cmd_google_container_list
      end

      desc 'Update and restart container in GCE'
      task :update do
        @commands << cmd_google_container_update
      end
    end
  end
end
