# frozen_string_literal: true

require 'rake'

namespace :dockerhub do
  namespace :takelbase do
    namespace :project do
      desc 'Create and deploy prod image to dockerhub'
      task prod: %w[git:warn
                    dockerhub:registry:login
                    rubylint
                    image:docker:takelbase:update
                    image:docker:takelbase:project:prod:from_base
                    image:docker:takelbase:project:prod:test
                    git:tag
                    dockerhub:registry:tag
                    dockerhub:registry:push]
    end
  end
end
