# frozen_string_literal: true

require 'rake'

namespace :google do
  namespace :gce do
    namespace :prod do |env|
      namespace :firewall do
        @gce_firewall.each do |task, command|
          desc "#{task} firewall rule in GCE"
          task task do
            @project['google_firewall_prod'].each do |rule|
              rule_name = "allow-#{rule['desc']}-#{rule['proto']}-" \
                          "#{rule['port']}-#{@project['google_repo']}" \
                          "-#{env.scope.head}"
              @commands << format(
                command,
                proto: rule['proto'],
                port: rule['port'],
                rule_name: rule_name
              )
            end
          end
        end
      end
    end
  end
end
