require 'rake'

namespace :google do
  desc 'Create and deploy image to dockerhub'
  task :prod => %w(test
                   local:container:stop
                   image:prod:build
                   image:prod:test
                   google:registry:tag
                   google:registry:push
                   google:container:update)
end
