require 'rake'

namespace :google do
  desc 'Create and deploy image to dockerhub'
  task :prod => %w(git:warn
                   test
                   local:container:stop
                   image:prod:build
                   image:prod:test
                   git:tag
                   google:prod:registry:tag
                   google:prod:registry:push
                   google:prod:container:update)
end
