require 'json'
require 'rake'

def _network_exists?
  cmd_docker_network_exist = 'docker network ls ' +
      '--quiet ' +
      "--filter name=#{ENV['HOSTNAME']}"
  network = `#{cmd_docker_network_exist}`
  not network.empty?
end

def _container_connected?
  cmd_docker_container_connected = 'docker inspect ' +
      '--format="{{json .NetworkSettings.Networks}}" ' +
      "#{ENV['HOSTNAME']}"
      networks = JSON.parse `#{cmd_docker_container_connected}`
  not networks[ENV['HOSTNAME']].nil?
end

cmd_local_network_create = 'docker network create ' +
    "#{ENV['HOSTNAME']}"

cmd_local_network_connect = 'docker network connect ' +
    "#{ENV['HOSTNAME']} " +
    "#{ENV['HOSTNAME']}"

namespace :local do
  namespace :network do

    desc 'Connect local network'
    task :connect do
      unless _container_connected?
        $commands << cmd_local_network_connect
      end
    end

    desc 'Create local network'
    task :create do
      unless _network_exists?
        $commands << cmd_local_network_create
      end
    end

    desc 'Start local network'
    task :start => %w(local:network:create
                      local:network:connect)

  end
end
