---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: molecule-takel-users
    image: takelage/takelbase
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: true
    groups:
      - molecule
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      interpreter_python: auto_silent
  inventory:
    group_vars:
      all:
        # clear text password: myrootpassword
        takel_users_root_password_hash: >-
          {{ lookup('file', '../support/myrootpassword_hash') }}
        takel_users_users:
          - myuser
        takel_users_userdata:
          myuser:
            id: 1500
            comment: My Testuser
            groups:
              - sudo
            ssh: >-
              {{ lookup('file', '../support/myuserssh_key') }}
            # clear text password: myuserpassword
            password_hash: >-
              {{ lookup('file', '../support/myuserpassword_hash') }}
verifier:
  name: testinfra
  additional_files_or_dirs:
    - ../../default/tests/test_*.py
  options:
    s: true
    v: true
scenario:
  name: role
  create_sequence:
    - create
  check_sequence:
    - destroy
    - create
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
