require 'rake'

cmd_google_registry_push = "docker push " +
    "#{$project['repo_google']}/#{$project['project_id']}/#{$project['project']}:#{$project['version']}"

cmd_google_registry_tag = "docker tag " +
    "#{$project['local_user']}/#{$project['project']}:prod #{$project['repo_google']}/#{$project['project_id']}/#{$project['project']}:#{$project['version']}"

namespace :google do
  namespace :registry do

    desc 'Push production image to google.com'
    task :push do
      $commands << cmd_google_registry_push
    end

    desc 'Tag production image for google.com'
    task :tag do
      $commands << cmd_google_registry_tag
    end

  end
end