# frozen_string_literal: true

require 'rake'

environment = 'prod'
target = "#{@project['google_repo']}-#{environment}"

cmd_google_firewall_delete = 'gcloud compute firewall-rules delete ' \
    '%<name>s ' \
    "--project=#{@project['project_id']}"

cmd_google_firewall_describe = 'gcloud compute firewall-rules describe ' \
    '%<name>s ' \
    "--project=#{@project['project_id']}"

cmd_google_firewall_disable = 'gcloud compute firewall-rules update ' \
    '%<name>s ' \
    '--disabled ' \
    "--project=#{@project['project_id']}"

cmd_google_firewall_enable = 'gcloud compute firewall-rules update ' \
    '%<name>s ' \
    '--no-disabled ' \
    "--project=#{@project['project_id']}"

cmd_google_firewall_list = 'gcloud compute firewall-rules list ' \
    "--project=#{@project['project_id']}"

cmd_google_firewall_create = 'gcloud compute firewall-rules create ' \
    '%<name>s ' \
    '--action=allow ' \
    '--rules %<proto>s:%<port>d ' \
    "--target-tags=#{target} " \
    "--project=#{@project['project_id']}"

# rubocop:disable Metrics/BlockLength
namespace :google do
  namespace :prod do
    namespace :firewall do
      desc 'Create firewall rule'
      task :create do
        @project['google_firewall_prod'].each do |rule|
          name = "allow-#{rule['desc']}-#{rule['proto']}-#{rule['port']}" \
                 "-#{target}"
          @commands << format(
            cmd_google_firewall_create,
            port: rule['port'],
            proto: rule['proto'],
            name: name
          )
        end
      end

      desc 'Delete firewall rule'
      task :delete do
        @project['google_firewall_prod'].each do |rule|
          name = "allow-#{rule['desc']}-#{rule['proto']}-#{rule['port']}" \
                 "-#{target}"
          @commands << format(
            cmd_google_firewall_delete,
            name: name
          )
        end
      end

      desc 'Describe firewall rule'
      task :describe do
        @project['google_firewall_prod'].each do |rule|
          name = "allow-#{rule['desc']}-#{rule['proto']}-#{rule['port']}-" \
                 "#{target}"
          @commands << format(
            cmd_google_firewall_describe,
            name: name
          )
        end
      end

      desc 'Disable firewall rule'
      task :disable do
        @project['google_firewall_prod'].each do |rule|
          name = "allow-#{rule['desc']}-#{rule['proto']}-#{rule['port']}-" \
                 "#{target}"
          @commands << format(
            cmd_google_firewall_disable,
            name: name
          )
        end
      end

      desc 'Enable firewall rule'
      task :enable do
        @project['google_firewall_prod'].each do |rule|
          name = "allow-#{rule['desc']}-#{rule['proto']}-#{rule['port']}-" \
                 "#{target}"
          @commands << format(
            cmd_google_firewall_enable,
            name: name
          )
        end
      end

      desc 'List firewall rules'
      task :list do
        @commands << cmd_google_firewall_list
      end
    end
  end
end
# rubocop:enable Metrics/BlockLength
