---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: molecule-takel-takelage-bit-test-image-${TAKELAGE_PROJECT_ENV:-prod}
    image: packer_local/takelage-bit:${TAKELAGE_PROJECT_ENV:-prod}
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: true
    groups:
      - ${TAKELAGE_PROJECT_ENV:-prod}
      - users
      - molecule
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      stdout_callback: yaml
      bin_ansible_callbacks: true
  inventory:
    links:
      group_vars: ../../group_vars/
verifier:
  name: testinfra
  options:
    # p: cacheprovider  # enable cache
    s: true  # capture output
    v: true
  additional_files_or_dirs:
    # integration
    - ../../../roles/*/molecule/default/tests/test_*.py
    # system
    - ../../../roles/*/molecule/default/system/test_*.py
dependency:
  name: shell
  command: rake features:cucumber[@${TAKELAGE_PROJECT_ENV:-prod}]
scenario:
  dependency_sequence:
    - dependency
  create_sequence:
    - create
  converge_sequence:
    - create
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - destroy
    - create
    - verify
    - syntax
    # - dependency
    - destroy
