---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: molecule-takel-takelage-bit-test-image-${TAKELAGE_PROJECT_ENV:-prod}
    # yamllint disable-line rule:line-length
    image: packer_local/takelage-bit-${TAKELAGE_PROJECT_IMG:-non}-${TAKELAGE_PROJECT_ENV:-prod}
    command: ${TAKELAGE_PROJECT_COMMAND:-/usr/bin/tail -f /dev/null}
    privileged: true
    pre_build_image: true
    groups:
      - ${TAKELAGE_PROJECT_ENV:-prod}
      - users
      - molecule
provisioner:
  name: ansible
  playbooks:
    converge: >-
      ../../${TAKELAGE_MOLECULE_CONVERGE_PLAYBOOK:-playbook-site.yml}
  config_options:
    defaults:
      interpreter_python: auto_silent
      stdout_callback: yaml
      bin_ansible_callbacks: true
  inventory:
    links:
      group_vars: ../../group_vars/
verifier:
  name: testinfra
  options:
    # p: cacheprovider  # enable cache
    s: true  # capture output
    v: true
  env:
    TESTVARS_ROLES_PLAYBOOKS: >-
      ${TAKELAGE_MOLECULE_VERIFIER_PLAYS:-../../playbook-site.yml}
  additional_files_or_dirs: ${TAKELAGE_MOLECULE_VERIFIER_FILES:-[]}
scenario:
  create_sequence:
    - create
  converge_sequence:
    - create
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - destroy
    - create
    - verify
    - syntax
    - destroy
