---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: molecule-takel-gcsfuse
    image: takelage/takelbase
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      interpreter_python: auto_silent
  inventory:
    group_vars:
      all:
        takel_gcsfuse_gcs_bucket_key: dummy_key
        takel_gcsfuse_mounts:
          - path: /my_mount_1
            bucket: my_bucket_1
          - path: /my_mount_2
            bucket: my_bucket_2
          - path: /my_mount_3
            bucket: my_bucket_3
verifier:
  name: testinfra
  additional_files_or_dirs:
    - ../system/test_*.py
  options:
    # p: cacheprovider
    s: true
    v: true
scenario:
  create_sequence:
    - create
    - prepare
  check_sequence:
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - prepare
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
