# frozen_string_literal: true

require 'rake'

@gce_registry = {
  push: 'docker push ' \
        "#{@project['google_user']}/" \
        "#{@project['google_id']}/" \
        "#{@project['google_repo']}:" \
        "#{@project['version']}",
  tag: 'docker tag ' \
        "#{@project['local_user']}/" \
        "#{@project['name']} " \
        "#{@project['google_user']}/#{@project['google_id']}/" \
        "#{@project['google_repo']}:" \
        "#{@project['version']}"
}

namespace :cloud do
  namespace :gce do |gce_env|
    subtasks(gce_env.scope.path) do
      namespace :registry do
        @gce_registry.each do |task, command|
          desc "#{task} production image to google.com"
          task task do
            @commands << command
          end
        end
      end
    end
  end
end
