require 'rake'

cmd_local_container_id = 'tau docker container check existing ' +
    "#{$project['project']} && " +
    "docker exec #{$project['project']} hostname" +
    '; true'

cmd_local_container_start = 'tau docker container check existing ' +
    "#{$project['project']} || " +
    'docker run ' +
    '--detach ' +
    "--name #{$project['project']} " +
    "--network #{ENV['HOSTNAME']} " +
    "--privileged " +
    '--rm ' +
    "#{$project['local_user']}/#{$project['project']}:prod" +
    '; true'

cmd_local_container_stop = 'tau docker container check existing ' +
    "#{$project['project']} && " +
    'docker stop ' +
    "#{$project['project']}" +
    '; true'

namespace :local do
  namespace :container do

    desc 'Get the local container id'
    task :id do
      $commands << cmd_local_container_id
    end

    desc 'Start local container'
    task :start do
      $commands << cmd_local_container_start
    end

    desc 'Stop local container'
    task :stop do
      $commands << cmd_local_container_stop
    end

  end
end
