require 'rake'

namespace :dockerhub do
  desc 'Create and deploy image to dockerhub'
  task :prod => %w(test
                   local:container:stop
                   image:prod:build
                   image:prod:test
                   git:tag
                   dockerhub:registry:tag
                   dockerhub:registry:login
                   dockerhub:registry:push)
end
